### ISSUE TITLE
Publish on the store?

### ISSUE THREAD

**Issue by uberkael** [OliverJAsh/vscode-smart-select-picker#1]
Hi!
This seems like a nice feature. 
Do you have any plans to publish it or continue its development?

**Comment by OliverJAsh** [comment]
Hey! I don't have plans to continue this at the moment. Unfortunately I ran into an issue with VS Code that was a bit of a showstopper for me personally: https://github.com/microsoft/vscode/issues/189972. I've opened [a PR to fix it](https://github.com/microsoft/vscode/pull/190091) but it's stalled in code review. Feel free to fork/copy the code and do whatever you want with it.

**Comment by uberkael** [comment]
Seems like the PR is almost ready, but don't have enough reviews.
I will use it for myself in the meantime.

Thanks!
